version: "3.8"
services:
  mysql-db: # Nombre de contenedor MYSQL
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Leche0123456!
      MYSQL_DATABASE: lab1
    ports:
      - 33060:3306
  nginx:
    container_name: nginx-proxy
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
  app:
    container_name: mysql-db-data
    image: matiassilvaal/lab1:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/lab1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=Leche0123456!
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db