version: "3.8"
services:
#  nginx:
#    container_name: nginx-proxy
#    image: nginx
#    restart: always
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app
#      - app-2
#      - app-3
  mysql-db: # Nombre de contenedor MYSQL
    image: mysql
    command: --secure-file-priv="" # Permite importar archivos CSV
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Leche0123456!
      MYSQL_DATABASE: lab1
    ports:
      - 33060:3306
  app:
    container_name: mysql-db-data
#    container_name: mysql-db-data-1
    image: matiassilvaal/lab1:latest
    ports:
      - "8080:8080"
#      - "8081:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql-db:3306/lab1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=Leche0123456!
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db
#  app-2:
#    container_name: mysql-db-data-2
#    image: matiassilvaal/lab1:latest
#    ports:
#      - "8082:8080"
#    environment:
#      - DB_URL=jdbc:mysql://mysql-db:3306/lab1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#      - DB_USERNAME=root
#      - DB_PASSWORD=Leche0123456!
#    deploy:
#      restart_policy:
#        condition: on-failure
#    depends_on:
#      - mysql-db
#  app-3:
#    container_name: mysql-db-data-3
#    image: matiassilvaal/lab1:latest
#    ports:
#      - "8083:8080"
#    environment:
#      - DB_URL=jdbc:mysql://mysql-db:3306/lab1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#      - DB_USERNAME=root
#      - DB_PASSWORD=Leche0123456!
#    deploy:
#      restart_policy:
#        condition: on-failure
#    depends_on:
#      - mysql-db