spring:
  application:
    name: lab1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/lab1
    #username: root
    #password: Leche0123456!
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}